const USERS_ACTION_TYPES = {
  SET_CURRENT_USER: 'users/SET_CURRENT_USER',
  SET_TOKEN: 'users/SET_TOKEN',
  LOGOUT: 'users/LOGOUT',
  SET_ACTIVE_USERS_LIST: 'users/SET_ACTIVE_USERS_LIST',
  DISABLE_USER: 'users/DISABLE_USER'
};

export default USERS_ACTION_TYPES;
